export const componentLibraryPublicComponentNames = [
  "Button",
  "Icon",
  "IconButton",
  "LinkButton",
  "ClipboardCopyButton",
  "Field",
  "Input",
  "NumberInput",
  "Textarea",
  "SearchInput",
  "Select",
  "MultiSelect",
  "SuggestInput",
  "Checkbox",
  "Switch",
  "SettingRow",
  "FieldProvenance",
  "LineNumberedEditor",
  "LockHint",
  "Badge",
  "Stamp",
  "StampRule",
  "EmptyState",
  "ErrorState",
  "OperationFeedback",
  "Highlight",
  "StatusBadge",
  "StateSurface",
  "StateView",
  "InlineAlert",
  "LiveRegion",
  "Skeleton",
  "EnvironmentBanner",
  "StatusSummaryPanel",
  "ReadbackPanel",
  "Text",
  "Heading",
  "Surface",
  "Divider",
  "AppStatusBar",
  "CollapsibleRegion",
  "DisclosurePanel",
  "SettingsLayout",
  "PageHierarchy",
  "KeyValueList",
  "DatePicker",
  "Tree",
  "DataGrid",
  "Menu",
  "Toast",
  "RadioGroup",
  "SettingChoice",
  "SettingsHostSwitcher",
  "Tabs",
  "Card",
  "Avatar",
  "Progress",
  "Stepper",
  "DefinitionList",
  "DictionaryTable",
  "ContentScope",
  "StatCard",
  "FilterBar",
  "TableShell",
  "TableToolbar",
  "DetailInspector",
  "SearchableList",
  "TemplateGallery",
  "Breadcrumb",
  "ModuleTabs",
  "SectionTabs",
  "SegmentedNav",
  "Pagination",
  "TopBar",
  "SideNav",
  "NavGroup",
  "NavItem",
  "ProductLauncher",
  "ProductSwitcher",
  "SkipLink",
  "TcrnBrandMark",
  "ProductLogo",
  "ProductLockup",
  "ShellBrandLockup",
  "ShellThemeToggle",
  "ShellLocaleMenu",
  "SideNavCollapseButton",
  "MobileNavToggle",
  "ProductShell",
  "ProductShellSearch",
  "DetailDrawer",
  "ActionDrawer",
  "Tooltip",
  "Popover",
  "Dialog",
  "ConfirmActionDialog",
  "RelationshipChip",
  "MachineToken",
  "MachineTokenCell",
  "SubNav",
  "SavedViewToolbar",
  "PageHeader",
  "ViewTabs",
  "QuickFilters",
  "RecordRow",
  "RecordTable",
  "SplitView",
  "InlineCreate",
  "RowGroup",
  "LaneBoard",
  "RelationGraph",
  "StagePipeline",
  "AttachmentList",
  "MetadataRail",
  "ActivityFeed",
  "DetailLayout",
  "RecordInspector",
  "TreeNav",
  "LabelSet",
  "DocumentCanvas",
  "TocRail",
  "InlineCommentList",
  "VersionHistory",
  "SearchResultList"
] as const;

export type ComponentLibraryPublicComponentName = (typeof componentLibraryPublicComponentNames)[number];

export const componentLibraryPublicUtilityNames = [
  "tcrnIconNames",
  "tcrnComponentCss",
  "tcrnProductLogoRegistry",
  "getTcrnProductLogoAsset",
  "tcrnSettingChoiceDecisionTable",
  "resolveSettingChoiceControl",
  "resolveFieldValueControl",
  "mountStaticOverlayBoundary",
  "useProductShellController",
  "validateContentScope",
  "evaluateConsumerEvidence"
] as const;

export type ComponentLibraryPublicUtilityName = (typeof componentLibraryPublicUtilityNames)[number];

export const componentLibraryDeferredPrototypeNames = [
  "DenseOperationsShellDemo",
  "KnowledgeBaseShellDemo",
  "CompactToolShellDemo"
] as const;

export type ComponentLibraryDeferredPrototypeName = (typeof componentLibraryDeferredPrototypeNames)[number];

export { cx, resolveDocumentLocale } from "./utils.js";
export * from "./components/Icon/index.js";
export * from "./components/Button/index.js";
export * from "./components/Clipboard/index.js";
export * from "./components/Typography/index.js";
export * from "./components/Form/index.js";
export * from "./components/Feedback/index.js";
export * from "./components/Navigation/index.js";
export * from "./components/Layout/index.js";
export * from "./components/DataDisplay/index.js";
export * from "./components/Overlay/index.js";
export * from "./verification/index.js";
